/*
 * Holdings APIs
 * Get customer holdings
 *
 * OpenAPI spec version: v1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.holdings2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * ErrorHeader
 */

public class ErrorHeader {
  @JsonProperty("audit")
  private QueryHeaderAudit audit = null;

  public ErrorHeader audit(QueryHeaderAudit audit) {
    this.audit = audit;
    return this;
  }

   /**
   * Get audit
   * @return audit
  **/
  @ApiModelProperty(value = "")
  public QueryHeaderAudit getAudit() {
    return audit;
  }

  public void setAudit(QueryHeaderAudit audit) {
    this.audit = audit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorHeader errorHeader = (ErrorHeader) o;
    return Objects.equals(this.audit, errorHeader.audit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorHeader {\n");
    
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

