/*
 * Holdings APIs
 * Get customer holdings
 *
 * OpenAPI spec version: v1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.holdings2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * HoldingsResponseBodyInnerPaymentTemplates
 */

public class HoldingsResponseBodyInnerPaymentTemplates {
  @JsonProperty("paymentTemplate")
  private String paymentTemplate = null;

  public HoldingsResponseBodyInnerPaymentTemplates paymentTemplate(String paymentTemplate) {
    this.paymentTemplate = paymentTemplate;
    return this;
  }

   /**
   * 
   * @return paymentTemplate
  **/
  @ApiModelProperty(value = "")
  public String getPaymentTemplate() {
    return paymentTemplate;
  }

  public void setPaymentTemplate(String paymentTemplate) {
    this.paymentTemplate = paymentTemplate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HoldingsResponseBodyInnerPaymentTemplates holdingsResponseBodyInnerPaymentTemplates = (HoldingsResponseBodyInnerPaymentTemplates) o;
    return Objects.equals(this.paymentTemplate, holdingsResponseBodyInnerPaymentTemplates.paymentTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HoldingsResponseBodyInnerPaymentTemplates {\n");
    
    sb.append("    paymentTemplate: ").append(toIndentedString(paymentTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

