/*
 * Holdings APIs
 * Get customer holdings
 *
 * OpenAPI spec version: v1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.holdings2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * HoldingsResponseBodyInner
 */

public class HoldingsResponseBodyInner {
  @JsonProperty("products")
  private List<HoldingsResponseBodyInnerProducts> products = null;

  @JsonProperty("productLineId")
  private String productLineId = null;

  @JsonProperty("totalAccountBalances")
  private BigDecimal totalAccountBalances = null;

  @JsonProperty("totalDepositBalances")
  private BigDecimal totalDepositBalances = null;

  @JsonProperty("totalLoanBalances")
  private BigDecimal totalLoanBalances = null;

  @JsonProperty("totalExtAccountBalances")
  private String totalExtAccountBalances = null;

  public HoldingsResponseBodyInner products(List<HoldingsResponseBodyInnerProducts> products) {
    this.products = products;
    return this;
  }

  public HoldingsResponseBodyInner addProductsItem(HoldingsResponseBodyInnerProducts productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * The product for which the pricing plan is applicable
   * @return products
  **/
  @ApiModelProperty(value = "The product for which the pricing plan is applicable")
  public List<HoldingsResponseBodyInnerProducts> getProducts() {
    return products;
  }

  public void setProducts(List<HoldingsResponseBodyInnerProducts> products) {
    this.products = products;
  }

  public HoldingsResponseBodyInner productLineId(String productLineId) {
    this.productLineId = productLineId;
    return this;
  }

   /**
   * The top level product line, which the product is ultimately attached to. May be a Temenos-defined product line such as ACCOUNTS, AGENT, BUNDLE, CONSENT, DEPOSITS, LENDING, REWARDS, etc. or one defined by the institution to manage external products.
   * @return productLineId
  **/
  @ApiModelProperty(value = "The top level product line, which the product is ultimately attached to. May be a Temenos-defined product line such as ACCOUNTS, AGENT, BUNDLE, CONSENT, DEPOSITS, LENDING, REWARDS, etc. or one defined by the institution to manage external products.")
  public String getProductLineId() {
    return productLineId;
  }

  public void setProductLineId(String productLineId) {
    this.productLineId = productLineId;
  }

  public HoldingsResponseBodyInner totalAccountBalances(BigDecimal totalAccountBalances) {
    this.totalAccountBalances = totalAccountBalances;
    return this;
  }

   /**
   * 
   * @return totalAccountBalances
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTotalAccountBalances() {
    return totalAccountBalances;
  }

  public void setTotalAccountBalances(BigDecimal totalAccountBalances) {
    this.totalAccountBalances = totalAccountBalances;
  }

  public HoldingsResponseBodyInner totalDepositBalances(BigDecimal totalDepositBalances) {
    this.totalDepositBalances = totalDepositBalances;
    return this;
  }

   /**
   * 
   * @return totalDepositBalances
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTotalDepositBalances() {
    return totalDepositBalances;
  }

  public void setTotalDepositBalances(BigDecimal totalDepositBalances) {
    this.totalDepositBalances = totalDepositBalances;
  }

  public HoldingsResponseBodyInner totalLoanBalances(BigDecimal totalLoanBalances) {
    this.totalLoanBalances = totalLoanBalances;
    return this;
  }

   /**
   * 
   * @return totalLoanBalances
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTotalLoanBalances() {
    return totalLoanBalances;
  }

  public void setTotalLoanBalances(BigDecimal totalLoanBalances) {
    this.totalLoanBalances = totalLoanBalances;
  }

  public HoldingsResponseBodyInner totalExtAccountBalances(String totalExtAccountBalances) {
    this.totalExtAccountBalances = totalExtAccountBalances;
    return this;
  }

   /**
   * 
   * @return totalExtAccountBalances
  **/
  @ApiModelProperty(value = "")
  public String getTotalExtAccountBalances() {
    return totalExtAccountBalances;
  }

  public void setTotalExtAccountBalances(String totalExtAccountBalances) {
    this.totalExtAccountBalances = totalExtAccountBalances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HoldingsResponseBodyInner holdingsResponseBodyInner = (HoldingsResponseBodyInner) o;
    return Objects.equals(this.products, holdingsResponseBodyInner.products) &&
        Objects.equals(this.productLineId, holdingsResponseBodyInner.productLineId) &&
        Objects.equals(this.totalAccountBalances, holdingsResponseBodyInner.totalAccountBalances) &&
        Objects.equals(this.totalDepositBalances, holdingsResponseBodyInner.totalDepositBalances) &&
        Objects.equals(this.totalLoanBalances, holdingsResponseBodyInner.totalLoanBalances) &&
        Objects.equals(this.totalExtAccountBalances, holdingsResponseBodyInner.totalExtAccountBalances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(products, productLineId, totalAccountBalances, totalDepositBalances, totalLoanBalances, totalExtAccountBalances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HoldingsResponseBodyInner {\n");
    
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    productLineId: ").append(toIndentedString(productLineId)).append("\n");
    sb.append("    totalAccountBalances: ").append(toIndentedString(totalAccountBalances)).append("\n");
    sb.append("    totalDepositBalances: ").append(toIndentedString(totalDepositBalances)).append("\n");
    sb.append("    totalLoanBalances: ").append(toIndentedString(totalLoanBalances)).append("\n");
    sb.append("    totalExtAccountBalances: ").append(toIndentedString(totalExtAccountBalances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

