/*
 * TC CHANNELS FT PUBLISHED API
 * TC CHANNELS FT PUBLISHED API
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.payments2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * ErrorHeader
 */

public class ErrorHeader {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("transactionStatus")
  private String transactionStatus = null;

  @JsonProperty("uniqueIdentifier")
  private String uniqueIdentifier = null;

  @JsonProperty("audit")
  private ScreenHeaderAudit audit = null;

  public ErrorHeader id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The Identifier of the record created
   * @return id
  **/
  @ApiModelProperty(value = "The Identifier of the record created")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ErrorHeader status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the API(success/failed)
   * @return status
  **/
  @ApiModelProperty(value = "Status of the API(success/failed)")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ErrorHeader transactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
    return this;
  }

   /**
   * The status of the transaction
   * @return transactionStatus
  **/
  @ApiModelProperty(value = "The status of the transaction")
  public String getTransactionStatus() {
    return transactionStatus;
  }

  public void setTransactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
  }

  public ErrorHeader uniqueIdentifier(String uniqueIdentifier) {
    this.uniqueIdentifier = uniqueIdentifier;
    return this;
  }

   /**
   * The unique identifier/Message Reference of the record created.
   * @return uniqueIdentifier
  **/
  @ApiModelProperty(value = "The unique identifier/Message Reference of the record created.")
  public String getUniqueIdentifier() {
    return uniqueIdentifier;
  }

  public void setUniqueIdentifier(String uniqueIdentifier) {
    this.uniqueIdentifier = uniqueIdentifier;
  }

  public ErrorHeader audit(ScreenHeaderAudit audit) {
    this.audit = audit;
    return this;
  }

   /**
   * Get audit
   * @return audit
  **/
  @ApiModelProperty(value = "")
  public ScreenHeaderAudit getAudit() {
    return audit;
  }

  public void setAudit(ScreenHeaderAudit audit) {
    this.audit = audit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorHeader errorHeader = (ErrorHeader) o;
    return Objects.equals(this.id, errorHeader.id) &&
        Objects.equals(this.status, errorHeader.status) &&
        Objects.equals(this.transactionStatus, errorHeader.transactionStatus) &&
        Objects.equals(this.uniqueIdentifier, errorHeader.uniqueIdentifier) &&
        Objects.equals(this.audit, errorHeader.audit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, transactionStatus, uniqueIdentifier, audit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorHeader {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    uniqueIdentifier: ").append(toIndentedString(uniqueIdentifier)).append("\n");
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

