/*
 * TC CHANNELS FT PUBLISHED API
 * TC CHANNELS FT PUBLISHED API
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.payments2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * OverrideBody
 */

public class OverrideBody {
  @JsonProperty("overrideDetails")
  private List<OverrideBodyOverrideDetails> overrideDetails = null;

  public OverrideBody overrideDetails(List<OverrideBodyOverrideDetails> overrideDetails) {
    this.overrideDetails = overrideDetails;
    return this;
  }

  public OverrideBody addOverrideDetailsItem(OverrideBodyOverrideDetails overrideDetailsItem) {
    if (this.overrideDetails == null) {
      this.overrideDetails = new ArrayList<>();
    }
    this.overrideDetails.add(overrideDetailsItem);
    return this;
  }

   /**
   * Get overrideDetails
   * @return overrideDetails
  **/
  @ApiModelProperty(value = "")
  public List<OverrideBodyOverrideDetails> getOverrideDetails() {
    return overrideDetails;
  }

  public void setOverrideDetails(List<OverrideBodyOverrideDetails> overrideDetails) {
    this.overrideDetails = overrideDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OverrideBody overrideBody = (OverrideBody) o;
    return Objects.equals(this.overrideDetails, overrideBody.overrideDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(overrideDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OverrideBody {\n");
    
    sb.append("    overrideDetails: ").append(toIndentedString(overrideDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

