ussd:
    cache:
        #port: 19409
        port: 6379
        #host: redis-19409.c246.us-east-1-4.ec2.cloud.redislabs.com
        #172.22.10.46
        host: 127.0.0.1
        password:
        default-ttl: 180

    api:
        #172.24.45.145:8888
        #172.24.45.145:8080
        #172.24.5.3:9085

        host: http://172.22.10.46:8888/tc-channels-api/api/v1.0.0
        host2: http://192.168.100.30:9080/irf-rp-services/v1.0.0
        host3: http://192.168.100.21:8888/tc-channels-api-ac/api/v1.0.2
        host4: http://192.168.100.21:8888/tc-channels-api-ac/api/v1.0.0
        host5: http://192.168.100.21:8888/tc-channels-api-ac-transfers/api/v1.0.0
        host6: http://192.168.100.21:8888/tc-thirdparty-api/api/v1.0.0
        host7: http://172.22.10.46:8888/tc-channels-internal-api/api/v1.0.0
        host8:  http://172.22.10.46:80/ussd-admin/



        #AUTHOR
        username: IRIS01
        password: 123432

authenticator:
    api:
        host: http://172.22.10.46:80/ussd-admin/
