/*
 * getAccountListAPI
 * getAccountListAPI
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.accountDetail.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BusinessQueryErrorResponse
 */
@ApiModel(description = "BusinessQueryErrorResponse")

public class BusinessQueryErrorResponse {
  @JsonProperty("header")
  private ErrorHeader header = null;

  @JsonProperty("error")
  private BusinessQueryErrorResponseBody error = null;

  public BusinessQueryErrorResponse header(ErrorHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(value = "")
  public ErrorHeader getHeader() {
    return header;
  }

  public void setHeader(ErrorHeader header) {
    this.header = header;
  }

  public BusinessQueryErrorResponse error(BusinessQueryErrorResponseBody error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public BusinessQueryErrorResponseBody getError() {
    return error;
  }

  public void setError(BusinessQueryErrorResponseBody error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessQueryErrorResponse businessQueryErrorResponse = (BusinessQueryErrorResponse) o;
    return Objects.equals(this.header, businessQueryErrorResponse.header) &&
        Objects.equals(this.error, businessQueryErrorResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessQueryErrorResponse {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

