/*
 * Transactions APIs
 * Get Transactions Details
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.transactions.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * AccountTransactionsResponseBodyInner
 */

public class AccountTransactionsResponseBodyInner {
  @JsonProperty("statementId")
  private String statementId = null;

  @JsonProperty("bookingDate")
  private LocalDate bookingDate = null;

  @JsonProperty("narrative")
  private String narrative = null;

  @JsonProperty("accountId")
  private String accountId = null;

  @JsonProperty("statementAmount")
  private BigDecimal statementAmount = null;

  @JsonProperty("currencyId")
  private String currencyId = null;

  @JsonProperty("accountName")
  private String accountName = null;

  @JsonProperty("companyId")
  private String companyId = null;

  @JsonProperty("imageDocId")
  private String imageDocId = null;

  @JsonProperty("notes")
  private String notes = null;

  @JsonProperty("imageId")
  private String imageId = null;

  @JsonProperty("statementBalance")
  private BigDecimal statementBalance = null;

  @JsonProperty("transactionReference")
  private String transactionReference = null;

  public AccountTransactionsResponseBodyInner statementId(String statementId) {
    this.statementId = statementId;
    return this;
  }

   /**
   * 
   * @return statementId
  **/
  @ApiModelProperty(value = "")
  public String getStatementId() {
    return statementId;
  }

  public void setStatementId(String statementId) {
    this.statementId = statementId;
  }

  public AccountTransactionsResponseBodyInner bookingDate(LocalDate bookingDate) {
    this.bookingDate = bookingDate;
    return this;
  }

   /**
   * The date on which the entry was generated. Normally, but not necessarily, the actual date at the time the entry is generated, e.g. if the previous day&#39;s business is still being processed after midnight, the actual date changes, but the run date is still the previous day.
   * @return bookingDate
  **/
  @ApiModelProperty(value = "The date on which the entry was generated. Normally, but not necessarily, the actual date at the time the entry is generated, e.g. if the previous day's business is still being processed after midnight, the actual date changes, but the run date is still the previous day.")
  public LocalDate getBookingDate() {
    return bookingDate;
  }

  public void setBookingDate(LocalDate bookingDate) {
    this.bookingDate = bookingDate;
  }

  public AccountTransactionsResponseBodyInner narrative(String narrative) {
    this.narrative = narrative;
    return this;
  }

   /**
   * The additional text printed on descriptive statements in addition to the standard narrative and/or reference
   * @return narrative
  **/
  @ApiModelProperty(value = "The additional text printed on descriptive statements in addition to the standard narrative and/or reference")
  public String getNarrative() {
    return narrative;
  }

  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }

  public AccountTransactionsResponseBodyInner accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * The identifier of the account. Often referred to as the account number, yet for consistency this is always referred to as accountId.
   * @return accountId
  **/
  @ApiModelProperty(value = "The identifier of the account. Often referred to as the account number, yet for consistency this is always referred to as accountId.")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public AccountTransactionsResponseBodyInner statementAmount(BigDecimal statementAmount) {
    this.statementAmount = statementAmount;
    return this;
  }

   /**
   * 
   * @return statementAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getStatementAmount() {
    return statementAmount;
  }

  public void setStatementAmount(BigDecimal statementAmount) {
    this.statementAmount = statementAmount;
  }

  public AccountTransactionsResponseBodyInner currencyId(String currencyId) {
    this.currencyId = currencyId;
    return this;
  }

   /**
   * The identifier of the curreny. The is the 3 letter ISO 4217 code of the currency.
   * @return currencyId
  **/
  @ApiModelProperty(value = "The identifier of the curreny. The is the 3 letter ISO 4217 code of the currency.")
  public String getCurrencyId() {
    return currencyId;
  }

  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  public AccountTransactionsResponseBodyInner accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * The name of the account that is displayed
   * @return accountName
  **/
  @ApiModelProperty(value = "The name of the account that is displayed")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public AccountTransactionsResponseBodyInner companyId(String companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * The identifier of the company, following the format CCGGGLLLL, where: CC is the country code, GGG is Company Group Code and LLLL is the Local Code. Country Code must be a valid countryCode, Company Group Code must be 3 numeric characters in the range 001-999 and must be a valid companyGroup. The Local Code is 4 numeric characters in the range 0001-9999, e.g. GB0010001
   * @return companyId
  **/
  @ApiModelProperty(value = "The identifier of the company, following the format CCGGGLLLL, where: CC is the country code, GGG is Company Group Code and LLLL is the Local Code. Country Code must be a valid countryCode, Company Group Code must be 3 numeric characters in the range 001-999 and must be a valid companyGroup. The Local Code is 4 numeric characters in the range 0001-9999, e.g. GB0010001")
  public String getCompanyId() {
    return companyId;
  }

  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }

  public AccountTransactionsResponseBodyInner imageDocId(String imageDocId) {
    this.imageDocId = imageDocId;
    return this;
  }

   /**
   * 
   * @return imageDocId
  **/
  @ApiModelProperty(value = "")
  public String getImageDocId() {
    return imageDocId;
  }

  public void setImageDocId(String imageDocId) {
    this.imageDocId = imageDocId;
  }

  public AccountTransactionsResponseBodyInner notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * 
   * @return notes
  **/
  @ApiModelProperty(value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public AccountTransactionsResponseBodyInner imageId(String imageId) {
    this.imageId = imageId;
    return this;
  }

   /**
   * The identifier of the image used for advertisement
   * @return imageId
  **/
  @ApiModelProperty(value = "The identifier of the image used for advertisement")
  public String getImageId() {
    return imageId;
  }

  public void setImageId(String imageId) {
    this.imageId = imageId;
  }

  public AccountTransactionsResponseBodyInner statementBalance(BigDecimal statementBalance) {
    this.statementBalance = statementBalance;
    return this;
  }

   /**
   * 
   * @return statementBalance
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getStatementBalance() {
    return statementBalance;
  }

  public void setStatementBalance(BigDecimal statementBalance) {
    this.statementBalance = statementBalance;
  }

  public AccountTransactionsResponseBodyInner transactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
    return this;
  }

   /**
   * The transaction reference identifier
   * @return transactionReference
  **/
  @ApiModelProperty(value = "The transaction reference identifier")
  public String getTransactionReference() {
    return transactionReference;
  }

  public void setTransactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountTransactionsResponseBodyInner accountTransactionsResponseBodyInner = (AccountTransactionsResponseBodyInner) o;
    return Objects.equals(this.statementId, accountTransactionsResponseBodyInner.statementId) &&
        Objects.equals(this.bookingDate, accountTransactionsResponseBodyInner.bookingDate) &&
        Objects.equals(this.narrative, accountTransactionsResponseBodyInner.narrative) &&
        Objects.equals(this.accountId, accountTransactionsResponseBodyInner.accountId) &&
        Objects.equals(this.statementAmount, accountTransactionsResponseBodyInner.statementAmount) &&
        Objects.equals(this.currencyId, accountTransactionsResponseBodyInner.currencyId) &&
        Objects.equals(this.accountName, accountTransactionsResponseBodyInner.accountName) &&
        Objects.equals(this.companyId, accountTransactionsResponseBodyInner.companyId) &&
        Objects.equals(this.imageDocId, accountTransactionsResponseBodyInner.imageDocId) &&
        Objects.equals(this.notes, accountTransactionsResponseBodyInner.notes) &&
        Objects.equals(this.imageId, accountTransactionsResponseBodyInner.imageId) &&
        Objects.equals(this.statementBalance, accountTransactionsResponseBodyInner.statementBalance) &&
        Objects.equals(this.transactionReference, accountTransactionsResponseBodyInner.transactionReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statementId, bookingDate, narrative, accountId, statementAmount, currencyId, accountName, companyId, imageDocId, notes, imageId, statementBalance, transactionReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountTransactionsResponseBodyInner {\n");
    
    sb.append("    statementId: ").append(toIndentedString(statementId)).append("\n");
    sb.append("    bookingDate: ").append(toIndentedString(bookingDate)).append("\n");
    sb.append("    narrative: ").append(toIndentedString(narrative)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    statementAmount: ").append(toIndentedString(statementAmount)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    imageDocId: ").append(toIndentedString(imageDocId)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    imageId: ").append(toIndentedString(imageId)).append("\n");
    sb.append("    statementBalance: ").append(toIndentedString(statementBalance)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

