/*
 * Transactions APIs
 * Get Transactions Details
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.transactions.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;

/**
 * TransactionDetailsResponseBodyInnerDebits
 */

public class TransactionDetailsResponseBodyInnerDebits {
  @JsonProperty("debitCurrencyId")
  private String debitCurrencyId = null;

  @JsonProperty("debitAmount")
  private String debitAmount = null;

  @JsonProperty("debitValueDate")
  private LocalDate debitValueDate = null;

  @JsonProperty("debitAccountId")
  private String debitAccountId = null;

  @JsonProperty("debitAccountIBAN")
  private String debitAccountIBAN = null;

  public TransactionDetailsResponseBodyInnerDebits debitCurrencyId(String debitCurrencyId) {
    this.debitCurrencyId = debitCurrencyId;
    return this;
  }

   /**
   * The identifier of the debit currency
   * @return debitCurrencyId
  **/
  @ApiModelProperty(value = "The identifier of the debit currency")
  public String getDebitCurrencyId() {
    return debitCurrencyId;
  }

  public void setDebitCurrencyId(String debitCurrencyId) {
    this.debitCurrencyId = debitCurrencyId;
  }

  public TransactionDetailsResponseBodyInnerDebits debitAmount(String debitAmount) {
    this.debitAmount = debitAmount;
    return this;
  }

   /**
   * 
   * @return debitAmount
  **/
  @ApiModelProperty(value = "")
  public String getDebitAmount() {
    return debitAmount;
  }

  public void setDebitAmount(String debitAmount) {
    this.debitAmount = debitAmount;
  }

  public TransactionDetailsResponseBodyInnerDebits debitValueDate(LocalDate debitValueDate) {
    this.debitValueDate = debitValueDate;
    return this;
  }

   /**
   * The date on which the Invocation amount will be debited for settlement
   * @return debitValueDate
  **/
  @ApiModelProperty(value = "The date on which the Invocation amount will be debited for settlement")
  public LocalDate getDebitValueDate() {
    return debitValueDate;
  }

  public void setDebitValueDate(LocalDate debitValueDate) {
    this.debitValueDate = debitValueDate;
  }

  public TransactionDetailsResponseBodyInnerDebits debitAccountId(String debitAccountId) {
    this.debitAccountId = debitAccountId;
    return this;
  }

   /**
   * The identifier of the debit account
   * @return debitAccountId
  **/
  @ApiModelProperty(value = "The identifier of the debit account")
  public String getDebitAccountId() {
    return debitAccountId;
  }

  public void setDebitAccountId(String debitAccountId) {
    this.debitAccountId = debitAccountId;
  }

  public TransactionDetailsResponseBodyInnerDebits debitAccountIBAN(String debitAccountIBAN) {
    this.debitAccountIBAN = debitAccountIBAN;
    return this;
  }

   /**
   * IBAN of the debit account
   * @return debitAccountIBAN
  **/
  @ApiModelProperty(value = "IBAN of the debit account")
  public String getDebitAccountIBAN() {
    return debitAccountIBAN;
  }

  public void setDebitAccountIBAN(String debitAccountIBAN) {
    this.debitAccountIBAN = debitAccountIBAN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionDetailsResponseBodyInnerDebits transactionDetailsResponseBodyInnerDebits = (TransactionDetailsResponseBodyInnerDebits) o;
    return Objects.equals(this.debitCurrencyId, transactionDetailsResponseBodyInnerDebits.debitCurrencyId) &&
        Objects.equals(this.debitAmount, transactionDetailsResponseBodyInnerDebits.debitAmount) &&
        Objects.equals(this.debitValueDate, transactionDetailsResponseBodyInnerDebits.debitValueDate) &&
        Objects.equals(this.debitAccountId, transactionDetailsResponseBodyInnerDebits.debitAccountId) &&
        Objects.equals(this.debitAccountIBAN, transactionDetailsResponseBodyInnerDebits.debitAccountIBAN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(debitCurrencyId, debitAmount, debitValueDate, debitAccountId, debitAccountIBAN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionDetailsResponseBodyInnerDebits {\n");
    
    sb.append("    debitCurrencyId: ").append(toIndentedString(debitCurrencyId)).append("\n");
    sb.append("    debitAmount: ").append(toIndentedString(debitAmount)).append("\n");
    sb.append("    debitValueDate: ").append(toIndentedString(debitValueDate)).append("\n");
    sb.append("    debitAccountId: ").append(toIndentedString(debitAccountId)).append("\n");
    sb.append("    debitAccountIBAN: ").append(toIndentedString(debitAccountIBAN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

