/*
 * Transactions APIs
 * Get Transactions Details
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.transactions.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * TransactionDetailsResponseBodyInnerBeneficiaries
 */

public class TransactionDetailsResponseBodyInnerBeneficiaries {
  @JsonProperty("beneficiaryIBAN")
  private String beneficiaryIBAN = null;

  @JsonProperty("beneficiaryAccountId")
  private String beneficiaryAccountId = null;

  @JsonProperty("beneficiaryCustomerId")
  private String beneficiaryCustomerId = null;

  @JsonProperty("beneficiaryBankName")
  private String beneficiaryBankName = null;

  public TransactionDetailsResponseBodyInnerBeneficiaries beneficiaryIBAN(String beneficiaryIBAN) {
    this.beneficiaryIBAN = beneficiaryIBAN;
    return this;
  }

   /**
   * The IBAN of the beneficiary&#39;s account
   * @return beneficiaryIBAN
  **/
  @ApiModelProperty(value = "The IBAN of the beneficiary's account")
  public String getBeneficiaryIBAN() {
    return beneficiaryIBAN;
  }

  public void setBeneficiaryIBAN(String beneficiaryIBAN) {
    this.beneficiaryIBAN = beneficiaryIBAN;
  }

  public TransactionDetailsResponseBodyInnerBeneficiaries beneficiaryAccountId(String beneficiaryAccountId) {
    this.beneficiaryAccountId = beneficiaryAccountId;
    return this;
  }

   /**
   * The identifier of the beneficiary account
   * @return beneficiaryAccountId
  **/
  @ApiModelProperty(value = "The identifier of the beneficiary account")
  public String getBeneficiaryAccountId() {
    return beneficiaryAccountId;
  }

  public void setBeneficiaryAccountId(String beneficiaryAccountId) {
    this.beneficiaryAccountId = beneficiaryAccountId;
  }

  public TransactionDetailsResponseBodyInnerBeneficiaries beneficiaryCustomerId(String beneficiaryCustomerId) {
    this.beneficiaryCustomerId = beneficiaryCustomerId;
    return this;
  }

   /**
   * The customer identifier where the beneficiary is a customer of the bank
   * @return beneficiaryCustomerId
  **/
  @ApiModelProperty(value = "The customer identifier where the beneficiary is a customer of the bank")
  public String getBeneficiaryCustomerId() {
    return beneficiaryCustomerId;
  }

  public void setBeneficiaryCustomerId(String beneficiaryCustomerId) {
    this.beneficiaryCustomerId = beneficiaryCustomerId;
  }

  public TransactionDetailsResponseBodyInnerBeneficiaries beneficiaryBankName(String beneficiaryBankName) {
    this.beneficiaryBankName = beneficiaryBankName;
    return this;
  }

   /**
   * 
   * @return beneficiaryBankName
  **/
  @ApiModelProperty(value = "")
  public String getBeneficiaryBankName() {
    return beneficiaryBankName;
  }

  public void setBeneficiaryBankName(String beneficiaryBankName) {
    this.beneficiaryBankName = beneficiaryBankName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionDetailsResponseBodyInnerBeneficiaries transactionDetailsResponseBodyInnerBeneficiaries = (TransactionDetailsResponseBodyInnerBeneficiaries) o;
    return Objects.equals(this.beneficiaryIBAN, transactionDetailsResponseBodyInnerBeneficiaries.beneficiaryIBAN) &&
        Objects.equals(this.beneficiaryAccountId, transactionDetailsResponseBodyInnerBeneficiaries.beneficiaryAccountId) &&
        Objects.equals(this.beneficiaryCustomerId, transactionDetailsResponseBodyInnerBeneficiaries.beneficiaryCustomerId) &&
        Objects.equals(this.beneficiaryBankName, transactionDetailsResponseBodyInnerBeneficiaries.beneficiaryBankName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beneficiaryIBAN, beneficiaryAccountId, beneficiaryCustomerId, beneficiaryBankName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionDetailsResponseBodyInnerBeneficiaries {\n");
    
    sb.append("    beneficiaryIBAN: ").append(toIndentedString(beneficiaryIBAN)).append("\n");
    sb.append("    beneficiaryAccountId: ").append(toIndentedString(beneficiaryAccountId)).append("\n");
    sb.append("    beneficiaryCustomerId: ").append(toIndentedString(beneficiaryCustomerId)).append("\n");
    sb.append("    beneficiaryBankName: ").append(toIndentedString(beneficiaryBankName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

