/*
 * Transactions APIs
 * Get Transactions Details
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.transactions.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;

/**
 * TransactionDetailsResponseBodyInnerCredits
 */

public class TransactionDetailsResponseBodyInnerCredits {
  @JsonProperty("creditCurrencyId")
  private String creditCurrencyId = null;

  @JsonProperty("creditAmount")
  private String creditAmount = null;

  @JsonProperty("creditValueDate")
  private LocalDate creditValueDate = null;

  @JsonProperty("creditAccountId")
  private String creditAccountId = null;

  @JsonProperty("creditAccountIBAN")
  private String creditAccountIBAN = null;

  public TransactionDetailsResponseBodyInnerCredits creditCurrencyId(String creditCurrencyId) {
    this.creditCurrencyId = creditCurrencyId;
    return this;
  }

   /**
   * The identifier of the credit currency
   * @return creditCurrencyId
  **/
  @ApiModelProperty(value = "The identifier of the credit currency")
  public String getCreditCurrencyId() {
    return creditCurrencyId;
  }

  public void setCreditCurrencyId(String creditCurrencyId) {
    this.creditCurrencyId = creditCurrencyId;
  }

  public TransactionDetailsResponseBodyInnerCredits creditAmount(String creditAmount) {
    this.creditAmount = creditAmount;
    return this;
  }

   /**
   * The amount to be credited in a payment transaction
   * @return creditAmount
  **/
  @ApiModelProperty(value = "The amount to be credited in a payment transaction")
  public String getCreditAmount() {
    return creditAmount;
  }

  public void setCreditAmount(String creditAmount) {
    this.creditAmount = creditAmount;
  }

  public TransactionDetailsResponseBodyInnerCredits creditValueDate(LocalDate creditValueDate) {
    this.creditValueDate = creditValueDate;
    return this;
  }

   /**
   * The value date applied to the credit side of a payment
   * @return creditValueDate
  **/
  @ApiModelProperty(value = "The value date applied to the credit side of a payment")
  public LocalDate getCreditValueDate() {
    return creditValueDate;
  }

  public void setCreditValueDate(LocalDate creditValueDate) {
    this.creditValueDate = creditValueDate;
  }

  public TransactionDetailsResponseBodyInnerCredits creditAccountId(String creditAccountId) {
    this.creditAccountId = creditAccountId;
    return this;
  }

   /**
   * The identifier of the credit account
   * @return creditAccountId
  **/
  @ApiModelProperty(value = "The identifier of the credit account")
  public String getCreditAccountId() {
    return creditAccountId;
  }

  public void setCreditAccountId(String creditAccountId) {
    this.creditAccountId = creditAccountId;
  }

  public TransactionDetailsResponseBodyInnerCredits creditAccountIBAN(String creditAccountIBAN) {
    this.creditAccountIBAN = creditAccountIBAN;
    return this;
  }

   /**
   * IBAN of the credit account
   * @return creditAccountIBAN
  **/
  @ApiModelProperty(value = "IBAN of the credit account")
  public String getCreditAccountIBAN() {
    return creditAccountIBAN;
  }

  public void setCreditAccountIBAN(String creditAccountIBAN) {
    this.creditAccountIBAN = creditAccountIBAN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionDetailsResponseBodyInnerCredits transactionDetailsResponseBodyInnerCredits = (TransactionDetailsResponseBodyInnerCredits) o;
    return Objects.equals(this.creditCurrencyId, transactionDetailsResponseBodyInnerCredits.creditCurrencyId) &&
        Objects.equals(this.creditAmount, transactionDetailsResponseBodyInnerCredits.creditAmount) &&
        Objects.equals(this.creditValueDate, transactionDetailsResponseBodyInnerCredits.creditValueDate) &&
        Objects.equals(this.creditAccountId, transactionDetailsResponseBodyInnerCredits.creditAccountId) &&
        Objects.equals(this.creditAccountIBAN, transactionDetailsResponseBodyInnerCredits.creditAccountIBAN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCurrencyId, creditAmount, creditValueDate, creditAccountId, creditAccountIBAN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionDetailsResponseBodyInnerCredits {\n");
    
    sb.append("    creditCurrencyId: ").append(toIndentedString(creditCurrencyId)).append("\n");
    sb.append("    creditAmount: ").append(toIndentedString(creditAmount)).append("\n");
    sb.append("    creditValueDate: ").append(toIndentedString(creditValueDate)).append("\n");
    sb.append("    creditAccountId: ").append(toIndentedString(creditAccountId)).append("\n");
    sb.append("    creditAccountIBAN: ").append(toIndentedString(creditAccountIBAN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

