/*
 * TC CHANNELS OTHER AC FT PUBLISHED API
 * TC CHANNELS OTHER AC FT PUBLISHED API
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.otherpayments.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * CreateFundsTransferOtherAcTrfBodyPaymentDetails
 */

public class CreateFundsTransferOtherAcTrfBodyPaymentDetails {
  @JsonProperty("paymentDetail")
  private String paymentDetail = null;

  public CreateFundsTransferOtherAcTrfBodyPaymentDetails paymentDetail(String paymentDetail) {
    this.paymentDetail = paymentDetail;
    return this;
  }

   /**
   * Indicates the payment details for the beneficiary to apply the payment.
   * @return paymentDetail
  **/
  @ApiModelProperty(value = "Indicates the payment details for the beneficiary to apply the payment.")
  public String getPaymentDetail() {
    return paymentDetail;
  }

  public void setPaymentDetail(String paymentDetail) {
    this.paymentDetail = paymentDetail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateFundsTransferOtherAcTrfBodyPaymentDetails createFundsTransferOtherAcTrfBodyPaymentDetails = (CreateFundsTransferOtherAcTrfBodyPaymentDetails) o;
    return Objects.equals(this.paymentDetail, createFundsTransferOtherAcTrfBodyPaymentDetails.paymentDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentDetail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateFundsTransferOtherAcTrfBodyPaymentDetails {\n");
    
    sb.append("    paymentDetail: ").append(toIndentedString(paymentDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

