/*
 * TC CHANNELS OTHER AC FT PUBLISHED API
 * TC CHANNELS OTHER AC FT PUBLISHED API
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.otherpayments.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * PayloadHeaderOverrideOverrideDetails
 */

public class PayloadHeaderOverrideOverrideDetails {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("responseCode")
  private String responseCode = null;

  public PayloadHeaderOverrideOverrideDetails id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier of the override.
   * @return id
  **/
  @ApiModelProperty(value = "The identifier of the override.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PayloadHeaderOverrideOverrideDetails description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The actual override message.
   * @return description
  **/
  @ApiModelProperty(value = "The actual override message.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PayloadHeaderOverrideOverrideDetails code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The code related to override message.
   * @return code
  **/
  @ApiModelProperty(value = "The code related to override message.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public PayloadHeaderOverrideOverrideDetails responseCode(String responseCode) {
    this.responseCode = responseCode;
    return this;
  }

   /**
   * The user input to accept/reject the override.
   * @return responseCode
  **/
  @ApiModelProperty(value = "The user input to accept/reject the override.")
  public String getResponseCode() {
    return responseCode;
  }

  public void setResponseCode(String responseCode) {
    this.responseCode = responseCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayloadHeaderOverrideOverrideDetails payloadHeaderOverrideOverrideDetails = (PayloadHeaderOverrideOverrideDetails) o;
    return Objects.equals(this.id, payloadHeaderOverrideOverrideDetails.id) &&
        Objects.equals(this.description, payloadHeaderOverrideOverrideDetails.description) &&
        Objects.equals(this.code, payloadHeaderOverrideOverrideDetails.code) &&
        Objects.equals(this.responseCode, payloadHeaderOverrideOverrideDetails.responseCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, code, responseCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayloadHeaderOverrideOverrideDetails {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

