/*
 * TC CHANNELS OTHER AC FT PUBLISHED API
 * TC CHANNELS OTHER AC FT PUBLISHED API
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.otherpayments.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * PayloadHeader
 */

public class PayloadHeader {
  @JsonProperty("override")
  private PayloadHeaderOverride override = null;

  @JsonProperty("audit")
  private PayloadHeaderAudit audit = null;

  public PayloadHeader override(PayloadHeaderOverride override) {
    this.override = override;
    return this;
  }

   /**
   * Get override
   * @return override
  **/
  @ApiModelProperty(value = "")
  public PayloadHeaderOverride getOverride() {
    return override;
  }

  public void setOverride(PayloadHeaderOverride override) {
    this.override = override;
  }

  public PayloadHeader audit(PayloadHeaderAudit audit) {
    this.audit = audit;
    return this;
  }

   /**
   * Get audit
   * @return audit
  **/
  @ApiModelProperty(value = "")
  public PayloadHeaderAudit getAudit() {
    return audit;
  }

  public void setAudit(PayloadHeaderAudit audit) {
    this.audit = audit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayloadHeader payloadHeader = (PayloadHeader) o;
    return Objects.equals(this.override, payloadHeader.override) &&
        Objects.equals(this.audit, payloadHeader.audit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(override, audit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayloadHeader {\n");
    
    sb.append("    override: ").append(toIndentedString(override)).append("\n");
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

