/*
 * TC CHANNELS OTHER AC FT PUBLISHED API
 * TC CHANNELS OTHER AC FT PUBLISHED API
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bank.ussd.apiclient.otherpayments.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ScreenErrorResponse
 */
@ApiModel(description = "ScreenErrorResponse")

public class ScreenErrorResponse {
  @JsonProperty("header")
  private ErrorHeader header = null;

  @JsonProperty("error")
  private ScreenErrorResponseBody error = null;

  @JsonProperty("override")
  private OverrideBody override = null;

  public ScreenErrorResponse header(ErrorHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(value = "")
  public ErrorHeader getHeader() {
    return header;
  }

  public void setHeader(ErrorHeader header) {
    this.header = header;
  }

  public ScreenErrorResponse error(ScreenErrorResponseBody error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public ScreenErrorResponseBody getError() {
    return error;
  }

  public void setError(ScreenErrorResponseBody error) {
    this.error = error;
  }

  public ScreenErrorResponse override(OverrideBody override) {
    this.override = override;
    return this;
  }

   /**
   * Get override
   * @return override
  **/
  @ApiModelProperty(value = "")
  public OverrideBody getOverride() {
    return override;
  }

  public void setOverride(OverrideBody override) {
    this.override = override;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreenErrorResponse screenErrorResponse = (ScreenErrorResponse) o;
    return Objects.equals(this.header, screenErrorResponse.header) &&
        Objects.equals(this.error, screenErrorResponse.error) &&
        Objects.equals(this.override, screenErrorResponse.override);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, error, override);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreenErrorResponse {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    override: ").append(toIndentedString(override)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

